import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 
  | 'ro' | 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' 
  | 'zh' | 'ja' | 'ko' | 'ar' | 'hi' | 'tr' | 'pl' | 'nl' 
  | 'sv' | 'uk' | 'cs' | 'hu' | 'bg' | 'el' | 'th' | 'vi' | 'id';

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'ro', name: 'Română', flag: 'ro' },
  { code: 'en', name: 'English', flag: 'gb' },
  { code: 'es', name: 'Español', flag: 'es' },
  { code: 'fr', name: 'Français', flag: 'fr' },
  { code: 'de', name: 'Deutsch', flag: 'de' },
  { code: 'it', name: 'Italiano', flag: 'it' },
  { code: 'pt', name: 'Português', flag: 'pt' },
  { code: 'ru', name: 'Русский', flag: 'ru' },
  { code: 'zh', name: '中文', flag: 'cn' },
  { code: 'ja', name: '日本語', flag: 'jp' },
  { code: 'ko', name: '한국어', flag: 'kr' },
  { code: 'ar', name: 'العربية', flag: 'sa' },
  { code: 'hi', name: 'हिन्दी', flag: 'in' },
  { code: 'tr', name: 'Türkçe', flag: 'tr' },
  { code: 'pl', name: 'Polski', flag: 'pl' },
  { code: 'nl', name: 'Nederlands', flag: 'nl' },
  { code: 'sv', name: 'Svenska', flag: 'se' },
  { code: 'uk', name: 'Українська', flag: 'ua' },
  { code: 'cs', name: 'Čeština', flag: 'cz' },
  { code: 'hu', name: 'Magyar', flag: 'hu' },
  { code: 'bg', name: 'Български', flag: 'bg' },
  { code: 'el', name: 'Ελληνικά', flag: 'gr' },
  { code: 'th', name: 'ไทย', flag: 'th' },
  { code: 'vi', name: 'Tiếng Việt', flag: 'vn' },
  { code: 'id', name: 'Bahasa Indonesia', flag: 'id' },
];

type TranslationKeys = keyof typeof translations.ro;

const translations = {
  ro: {
    'nav.home': 'Acasă',
    'nav.life': 'Viața de Licean',
    'nav.hobbies': 'Hobby-uri',
    'nav.advice': 'Relații',
    'nav.forum': 'Forum',
    'nav.qa': 'Întreabă',
    'nav.archive': 'Arhivă',
    'nav.login': 'Autentificare',
    'nav.logout': 'Deconectare',
    'nav.darkmode': 'Mod întunecat',
    'nav.lightmode': 'Mod luminos',
    'nav.language': 'Limbă',
    'hero.title': 'Jurnalul unui adolescent de treabă',
    'hero.subtitle': 'Un loc sigur pentru gândurile tale, prieteni noi și schimburi de idei.',
    'latest.articles': 'Cele mai noi articole',
    'btn.readmore': 'Citește mai mult',
    'btn.create': 'Scrie un articol',
    'btn.back': 'Înapoi',
    'btn.cancel': 'Anulează',
    'btn.delete': 'Șterge',
    'btn.like': 'Apreciază',
    'btn.submit': 'Trimite',
    'btn.save': 'Salvează',
    'auth.login.title': 'Intră în cont',
    'auth.register.title': 'Creează cont nou',
    'auth.join': 'Alătură-te comunității!',
    'auth.email': 'Email',
    'auth.password': 'Parolă',
    'auth.username': 'Nume de utilizator',
    'auth.password.min': 'Min. 6 caractere',
    'auth.accept.terms': 'Accept',
    'auth.terms.link': 'Termenii și Condițiile',
    'auth.and': 'și',
    'auth.privacy.link': 'Politica de Confidențialitate',
    'auth.google': 'Conectează-te cu Google',
    'auth.login.prompt': 'Autentifică-te pentru a participa',
    'no.posts': 'Încă nu sunt postări aici.',
    'no.posts.cta': 'Începe să scrii propriile tale articole chiar acum.',
    'create.post.title': 'Titlu articol',
    'create.post.content': 'Despre ce vrei să scrii azi?',
    'create.post.submit': 'Publică',
    'category.liceu': 'Viața de Licean',
    'category.hobby': 'Hobby-uri și Pasiuni',
    'category.sfaturi': 'Relații',
    'category.general': 'General',
    'editor.title': 'Scrie un articol nou',
    'editor.title.edit': 'Editează articolul',
    'editor.title.placeholder': 'Un titlu captivant pentru articolul tău...',
    'editor.section': 'Secțiune',
    'editor.content.placeholder': 'Începe să scrii aici... Folosește bara de instrumente pentru formatare.',
    'editor.published': 'Articolul a fost publicat!',
    'editor.updated': 'Articolul a fost actualizat!',
    'editor.redirect': 'Vei fi redirecționat în câteva secunde...',
    'btn.edit': 'Editează',
    'btn.update': 'Actualizează',
    'share.title': 'Distribuie articolul',
    'share.copy': 'Copiază linkul',
    'share.copied': 'Link copiat!',
    'share.whatsapp': 'WhatsApp',
    'share.facebook': 'Facebook',
    'share.twitter': 'X (Twitter)',
    'share.linkedin': 'LinkedIn',
    'article.views': 'vizualizări',
    'article.shares': 'distribuiri',
    'article.comments': 'Comentarii',
    'article.add.comment': 'Adaugă un comentariu...',
    'article.post.comment': 'Postează comentariul',
    'article.login.comment': 'Autentifică-te pentru a participa la discuție.',
    'forum.subtitle': 'Alătură-te conversației. Conectează-te cu alți tineri și fă parte din comunitate.',
    'forum.all': 'Toate',
    'forum.general': 'Discuții Generale',
    'forum.general.desc': 'Orice și oricât.',
    'forum.school': 'Școală & Teme',
    'forum.school.desc': 'Ajutor la matematică, eseuri sau povești despre profesori.',
    'forum.gaming': 'Gaming',
    'forum.gaming.desc': 'LoL, CS2, Minecraft și altele.',
    'forum.music': 'Muzică & Artă',
    'forum.music.desc': 'Împărtășește playlist-urile sau desenele tale.',
    'forum.tech': 'Tech & Coding',
    'forum.tech.desc': 'Pentru pasionații de tehnologie.',
    'forum.new.thread': 'Începe un subiect nou',
    'forum.new.topic': 'Subiect nou',
    'forum.topic.title': 'Titlu',
    'forum.topic.title.placeholder': 'Ce ai în minte?',
    'forum.category': 'Categorie',
    'forum.create.topic': 'Creează subiectul',
    'forum.login.post': 'Autentifică-te pentru a posta',
    'forum.no.topics': 'Nu sunt subiecte încă. Începe primul fir de discuție!',
    'forum.replies': 'răspunsuri',
    'forum.back': 'Înapoi la Forum',
    'forum.started.by': 'Început de',
    'forum.reply.count': 'Răspunsuri',
    'forum.no.replies': 'Nu sunt răspunsuri încă. Fii primul care răspunde!',
    'forum.write.reply': 'Scrie un răspuns...',
    'forum.reply': 'Răspunde',
    'forum.login.reply': 'Autentifică-te pentru a răspunde.',
    'qa.subtitle': 'Întrebări anonime, răspunsuri reale. Întreabă orice despre școală, viață sau orice altceva.',
    'qa.placeholder': 'Scrie întrebarea ta aici...',
    'qa.ask': 'Întreabă',
    'qa.recent': 'Întrebări recente',
    'qa.no.questions': 'Nu sunt întrebări încă. Fii primul care întreabă!',
    'qa.asked.by': 'Întrebat de',
    'qa.answered': 'Răspuns',
    'qa.pending': 'În așteptare',
    'qa.answer.label': 'Răspuns:',
    'qa.admin.answer': 'Scrie un răspuns...',
    'qa.admin.submit': 'Trimite',
    'qa.admin.cancel': 'Anulează',
    'qa.admin.btn': 'Răspunde ca Admin',
    'qa.anonymous': 'Anonim',
    'qa.delete': 'Șterge întrebarea',
    'qa.delete.confirm.title': 'Confirmare ștergere',
    'qa.delete.confirm.message': 'Ești sigur că vrei să ștergi această întrebare? Această acțiune nu poate fi anulată.',
    'qa.delete.confirm.yes': 'Da, șterge',
    'qa.delete.confirm.no': 'Anulează',
    'qa.delete.success': 'Întrebarea a fost ștearsă cu succes.',
    'qa.approve': 'Aprobă',
    'qa.approve.success': 'Întrebarea a fost aprobată.',
    'qa.reject': 'Refuză',
    'qa.reject.success': 'Întrebarea a fost refuzată.',
    'qa.withdraw': 'Retrage',
    'qa.withdraw.success': 'Întrebarea ta a fost retrasă.',
    'qa.waiting.approval': 'Întrebarea ta a fost trimisă și va apărea după aprobare.',
    'qa.status.waiting': 'Așteaptă aprobare',
    'qa.my.pending': 'Întrebarea mea (în așteptare)',
    'qa.delete.forbidden': 'Nu poți șterge această întrebare deoarece nu îți aparține.',
    'archive.search': 'Caută articole...',
    'archive.all': 'Toate',
    'archive.no.results': 'Nu s-au găsit articole.',
    'archive.by': 'de',
    'section.login.write': 'Autentifică-te pentru a scrie',
    'privacy.title': 'Politica de Confidențialitate',
    'privacy.updated': 'Ultima actualizare:',
    'privacy.s1.title': '1. Introducere',
    'privacy.s1.text': 'Bine ai venit la Jurnalul unui adolescent de treabă. Respectăm confidențialitatea ta și ne angajăm să protejăm datele tale personale. Această politică de confidențialitate explică ce informații colectăm, cum le folosim și care sunt drepturile tale.',
    'privacy.s2.title': '2. Datele pe care le colectăm',
    'privacy.s2.text': 'Putem colecta următoarele tipuri de date personale:',
    'privacy.s2.i1': 'Informații de cont: numele de utilizator, adresa de email și parola (stocată criptat).',
    'privacy.s2.i2': 'Informații de profil: avatar, informații furnizate prin conectare cu Google.',
    'privacy.s2.i3': 'Conținut generat: articole, comentarii, postări pe forum și întrebări Q&A.',
    'privacy.s2.i4': 'Date tehnice: adresa IP, tipul browserului și cookie-urile de sesiune.',
    'privacy.s3.title': '3. Cum folosim datele',
    'privacy.s3.text': 'Folosim datele colectate pentru:',
    'privacy.s3.i1': 'Crearea și gestionarea contului tău.',
    'privacy.s3.i2': 'Furnizarea funcționalităților platformei (postări, comentarii, forum).',
    'privacy.s3.i3': 'Îmbunătățirea experienței utilizatorilor.',
    'privacy.s3.i4': 'Asigurarea securității platformei.',
    'privacy.s4.title': '4. Partajarea datelor',
    'privacy.s4.text': 'Nu vindem, închiriem sau partajăm datele tale personale cu terți în scopuri de marketing. Putem partaja date doar în următoarele situații:',
    'privacy.s4.i1': 'Cu furnizori de servicii (hosting, autentificare) care ne ajută să operăm platforma.',
    'privacy.s4.i2': 'Când suntem obligați prin lege.',
    'privacy.s5.title': '5. Cookie-uri',
    'privacy.s5.text': 'Folosim cookie-uri esențiale pentru funcționarea sesiunilor de autentificare. Aceste cookie-uri sunt necesare pentru a-ți menține sesiunea activă pe platformă.',
    'privacy.s6.title': '6. Securitatea datelor',
    'privacy.s6.text': 'Parolele sunt criptate folosind bcrypt cu salt de 12 runde. Sesiunile sunt securizate și stocate pe server. Folosim protecția HTTPS pentru transmiterea datelor.',
    'privacy.s7.title': '7. Drepturile tale',
    'privacy.s7.text': 'Ai dreptul de a:',
    'privacy.s7.i1': 'Solicita accesul la datele tale personale.',
    'privacy.s7.i2': 'Solicita ștergerea contului și a datelor asociate.',
    'privacy.s7.i3': 'Retrage consimțământul pentru prelucrarea datelor.',
    'privacy.s8.title': '8. Modificări ale politicii',
    'privacy.s8.text': 'Putem actualiza această politică periodic. Te vom notifica despre modificări semnificative prin intermediul platformei.',
    'privacy.s9.title': '9. Contact',
    'privacy.s9.text': 'Pentru orice întrebări legate de confidențialitate, ne poți contacta prin intermediul platformei.',
    'terms.title': 'Termeni și Condiții',
    'terms.updated': 'Ultima actualizare:',
    'terms.s1.title': '1. Acceptarea termenilor',
    'terms.s1.text': 'Prin crearea unui cont pe Jurnalul unui adolescent de treabă, accepți acești termeni și condiții în totalitate. Dacă nu ești de acord cu acești termeni, te rugăm să nu folosești platforma.',
    'terms.s2.title': '2. Eligibilitate',
    'terms.s2.text': 'Platforma este destinată adolescenților și tinerilor. Prin utilizarea platformei, confirmi că ai cel puțin 13 ani sau că ai acordul părintelui/tutorelui legal.',
    'terms.s3.title': '3. Contul de utilizator',
    'terms.s3.text': 'Prin crearea unui cont, te angajezi să:',
    'terms.s3.i1': 'Furnizezi informații corecte și actualizate.',
    'terms.s3.i2': 'Păstrezi confidențialitatea parolei tale.',
    'terms.s3.i3': 'Notifici imediat orice utilizare neautorizată a contului.',
    'terms.s4.title': '4. Conținut utilizator',
    'terms.s4.text': 'Ești responsabil pentru tot conținutul pe care îl postezi pe platformă. Este interzis să publici:',
    'terms.s4.i1': 'Conținut ilegal, hărțuitor sau discriminatoriu.',
    'terms.s4.i2': 'Informații false sau înșelătoare.',
    'terms.s4.i3': 'Conținut care încalcă drepturile de autor ale altor persoane.',
    'terms.s4.i4': 'Spam sau publicitate neautorizată.',
    'terms.s4.i5': 'Conținut explicit sau inadecvat pentru minori.',
    'terms.s5.title': '5. Drepturi de proprietate intelectuală',
    'terms.s5.text': 'Păstrezi drepturile de autor asupra conținutului tău original. Prin postarea pe platformă, ne acorzi o licență neexclusivă pentru a afișa conținutul pe platformă.',
    'terms.s6.title': '6. Moderare',
    'terms.s6.text': 'Ne rezervăm dreptul de a șterge orice conținut care încalcă acești termeni și de a suspenda sau șterge conturile care încalcă regulile platformei, fără notificare prealabilă.',
    'terms.s7.title': '7. Limitarea răspunderii',
    'terms.s7.text': 'Platforma este furnizată „ca atare". Nu garantăm disponibilitatea continuă a serviciului. Nu suntem responsabili pentru pierderi de date sau daune indirecte.',
    'terms.s8.title': '8. Modificări ale termenilor',
    'terms.s8.text': 'Putem modifica acești termeni în orice moment. Continuarea utilizării platformei după modificare constituie acceptarea noilor termeni.',
    'terms.s9.title': '9. Reziliere',
    'terms.s9.text': 'Poți închide contul în orice moment. Ne rezervăm dreptul de a rezilia accesul la platformă în caz de încălcare a termenilor.',
    'terms.s10.title': '10. Legislație aplicabilă',
    'terms.s10.text': 'Acești termeni sunt guvernați de legislația din România.',
    'nav.profile': 'Profilul meu',
    'profile.notfound': 'Utilizatorul nu a fost găsit',
    'profile.joined': 'Membru din',
    'profile.role.admin': 'Administrator',
    'profile.role.user': 'Utilizator',
    'profile.stat.topics': 'Subiecte forum',
    'profile.stat.replies': 'Răspunsuri forum',
    'profile.stat.articles': 'Articole publicate',
    'profile.published.articles': 'Articole publicate',
    'profile.forum.activity': 'Activitate forum',
    'profile.danger.zone': 'Zonă periculoasă',
    'profile.delete.warning': 'Ștergerea contului este permanentă și ireversibilă. Toate datele tale personale vor fi eliminate, iar conținutul tău va fi anonimizat.',
    'profile.delete.btn': 'Șterge contul',
    'profile.delete.confirm.title': 'Confirmare ștergere cont',
    'profile.delete.confirm.desc': 'Această acțiune este ireversibilă. Contul tău și toate datele asociate vor fi șterse permanent. Conținutul generat va fi anonimizat.',
    'profile.delete.password.placeholder': 'Introdu parola pentru confirmare',
    'profile.delete.confirm.btn': 'Șterge definitiv contul',
    'profile.deleted.title': 'Cont șters',
    'profile.deleted.desc': 'Contul tău a fost șters cu succes.',
    'profile.delete.error': 'Eroare la ștergerea contului',
    'editor.forbidden.title': 'Acces interzis',
    'editor.forbidden.desc': 'Doar administratorii pot crea articole. Dacă crezi că ar trebui să ai acces, contactează un administrator.',
    'notfound.title': 'Pagina nu a fost găsită',
    'notfound.text': 'Ne pare rău, pagina pe care o cauți nu există.',
    'notfound.back': 'Înapoi acasă',
    'footer.rights': 'Toate drepturile rezervate.',
    'footer.privacy': 'Politica de Confidențialitate',
    'footer.terms': 'Termeni și Condiții',
    'nav.admin': 'Panou Admin',
    'admin.title': 'Panou de Administrare',
    'admin.forbidden.desc': 'Doar administratorii au acces la panoul de administrare.',
    'admin.pending': 'rapoarte în așteptare',
    'admin.stat.users': 'Utilizatori',
    'admin.stat.posts': 'Articole',
    'admin.stat.comments': 'Comentarii',
    'admin.stat.reports': 'Rapoarte active',
    'admin.stat.topics': 'Subiecte forum',
    'admin.tab.users': 'Utilizatori',
    'admin.tab.content': 'Conținut',
    'admin.tab.reports': 'Rapoarte',
    'admin.tab.logs': 'Loguri',
    'admin.users.title': 'Gestionare utilizatori',
    'admin.users.search': 'Caută utilizatori...',
    'admin.promote': 'Promovează',
    'admin.demote': 'Retrogradează',
    'admin.block': 'Blochează',
    'admin.unblock': 'Deblochează',
    'admin.blocked': 'Blocat',
    'admin.role.updated': 'Rol actualizat cu succes',
    'admin.user.blocked': 'Utilizator blocat cu succes',
    'admin.user.unblocked': 'Utilizator deblocat cu succes',
    'admin.user.deleted': 'Utilizator șters cu succes',
    'admin.error': 'Eroare',
    'admin.no.users': 'Nu sunt utilizatori.',
    'admin.confirm.delete.user': 'Ești sigur că vrei să ștergi acest utilizator? Acțiunea este ireversibilă.',
    'admin.articles': 'Articole',
    'admin.comments': 'Comentarii',
    'admin.hidden': 'Ascuns',
    'admin.content.updated': 'Conținut actualizat',
    'admin.post.deleted': 'Articol șters',
    'admin.comment.deleted': 'Comentariu șters',
    'admin.no.posts': 'Nu sunt articole.',
    'admin.no.comments': 'Nu sunt comentarii.',
    'admin.confirm.delete.post': 'Ești sigur că vrei să ștergi acest articol?',
    'admin.confirm.delete.comment': 'Ești sigur că vrei să ștergi acest comentariu?',
    'admin.reports.title': 'Conținut raportat',
    'admin.report.pending': 'În așteptare',
    'admin.report.resolved.label': 'Rezolvat',
    'admin.report.dismissed': 'Respins',
    'admin.reported.by': 'Raportat de',
    'admin.resolve': 'Rezolvă',
    'admin.dismiss': 'Respinge',
    'admin.report.resolved': 'Raport rezolvat',
    'admin.no.reports': 'Nu sunt rapoarte.',
    'admin.logs.title': 'Loguri de activitate',
    'admin.no.logs': 'Nu sunt loguri de activitate.',
    'admin.block.title': 'Blochează utilizatorul',
    'admin.block.desc': 'Utilizatorul blocat nu va putea posta, comenta sau se autentifica.',
    'admin.block.reason': 'Motivul blocării',
    'admin.block.reason.placeholder': 'Introdu motivul blocării...',
    'admin.block.until': 'Blocat până la (opțional)',
    'admin.block.permanent.note': 'Lasă gol pentru blocare permanentă.',
    'admin.gdpr.title': 'Conformitate GDPR',
    'admin.gdpr.retention.title': 'Politica de retenție a datelor',
    'admin.gdpr.retention.text': 'Datele utilizatorilor sunt stocate pe durata existenței contului. La ștergerea contului, datele personale sunt anonimizate sau șterse complet, conform preferinței utilizatorului. Cookie-urile de sesiune expiră după 30 de zile.',
    'admin.gdpr.rights.title': 'Drepturile utilizatorilor',
    'admin.gdpr.rights.access': 'Dreptul de acces la datele personale',
    'admin.gdpr.rights.rectification': 'Dreptul la rectificarea datelor',
    'admin.gdpr.rights.erasure': 'Dreptul la ștergere (dreptul de a fi uitat)',
    'admin.gdpr.rights.portability': 'Dreptul la portabilitatea datelor (export JSON)',
    'admin.gdpr.rights.object': 'Dreptul de opoziție la prelucrarea datelor',
    'admin.gdpr.export.title': 'Export date utilizator',
    'admin.gdpr.export.text': 'Utilizatorii pot exporta toate datele lor personale în format JSON din pagina de profil.',
    'admin.gdpr.export.note': 'Endpoint: GET /api/auth/export-data (necesită autentificare)',
    'report.btn': 'Raportează',
    'report.reason.placeholder': 'Descrie motivul raportării...',
    'report.submitted': 'Raportul a fost trimis cu succes.',
    'profile.export.btn': 'Exportă datele mele',
    'profile.export.desc': 'Descarcă toate datele tale personale în format JSON (conform GDPR).',
    'forum.topic.delete': 'Șterge firul de discuție',
    'forum.topic.delete.confirm.title': 'Șterge firul de discuție',
    'forum.topic.delete.confirm.desc': 'Ești sigur? Toate răspunsurile din acest fir vor fi șterse permanent.',
    'report.title': 'Raportează conținut',
    'report.desc': 'Descrie de ce raportezi acest conținut. Adminii vor fi notificați.',
    'report.confirm': 'Trimite raportul',
    'nav.notifications': 'Notificări',
    'nav.notif.markall': 'Marchează toate',
    'nav.notif.empty': 'Nu ai notificări noi.',
    'qa.login.required': 'Trebuie să fii autentificat pentru a pune o întrebare.',
    'archive.restricted.title': 'Acces restricționat',
    'archive.restricted.desc': 'Secțiunea Arhivă este disponibilă doar pentru administratori.',
    'profile.edit.title': 'Editează profilul',
    'profile.edit.username': 'Username nou',
    'profile.edit.username.placeholder': 'Introdu noul username...',
    'profile.edit.username.hint': 'Doar litere, cifre și underscore (_). Între 3-30 caractere.',
    'profile.edit.current.password': 'Parola curentă',
    'profile.edit.current.password.placeholder': 'Parola ta actuală...',
    'profile.edit.new.password': 'Parolă nouă',
    'profile.edit.new.password.placeholder': 'Noua parolă (min. 6 caractere)...',
    'profile.edit.confirm.password': 'Confirmă parola nouă',
    'profile.edit.confirm.password.placeholder': 'Repetă noua parolă...',
    'profile.edit.save': 'Salvează modificările',
    'profile.edit.success': 'Profilul a fost actualizat cu succes!',
    'profile.edit.error': 'Eroare la actualizarea profilului',
    'profile.edit.passwords.mismatch': 'Parolele noi nu coincid',
    'profile.edit.no.changes': 'Nicio modificare detectată',
    'profile.edit.google.note': 'Contul tău este conectat prin Google. Nu poți schimba parola direct.',
  },
  en: {
    'nav.home': 'Home',
    'nav.life': 'High School Life',
    'nav.hobbies': 'Hobbies',
    'nav.advice': 'Relationships',
    'nav.forum': 'Forum',
    'nav.qa': 'Q&A',
    'nav.archive': 'Archive',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.darkmode': 'Dark mode',
    'nav.lightmode': 'Light mode',
    'nav.language': 'Language',
    'hero.title': 'Diary of a Cool Teen',
    'hero.subtitle': 'A safe place for your thoughts, new friends, and real advice.',
    'latest.articles': 'Latest Articles',
    'btn.readmore': 'Read More',
    'btn.create': 'Write an Article',
    'btn.back': 'Back',
    'btn.cancel': 'Cancel',
    'btn.delete': 'Delete',
    'btn.like': 'Like',
    'btn.submit': 'Submit',
    'btn.save': 'Save',
    'auth.login.title': 'Login',
    'auth.register.title': 'Create Account',
    'auth.join': 'Join the community!',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.password.min': 'Min. 6 characters',
    'auth.accept.terms': 'I accept the',
    'auth.terms.link': 'Terms and Conditions',
    'auth.and': 'and',
    'auth.privacy.link': 'Privacy Policy',
    'auth.google': 'Sign in with Google',
    'auth.login.prompt': 'Log in to participate',
    'no.posts': 'No posts here yet.',
    'no.posts.cta': 'Start writing your own articles right now.',
    'create.post.title': 'Article Title',
    'create.post.content': 'What do you want to write about today?',
    'create.post.submit': 'Publish',
    'category.liceu': 'High School Life',
    'category.hobby': 'Hobbies & Passions',
    'category.sfaturi': 'Relationships',
    'category.general': 'General',
    'editor.title': 'Write a new article',
    'editor.title.edit': 'Edit article',
    'editor.title.placeholder': 'A captivating title for your article...',
    'editor.section': 'Section',
    'editor.content.placeholder': 'Start writing here... Use the toolbar for formatting.',
    'editor.published': 'Article published!',
    'editor.updated': 'Article updated!',
    'editor.redirect': 'You will be redirected in a few seconds...',
    'btn.edit': 'Edit',
    'btn.update': 'Update',
    'share.title': 'Share article',
    'share.copy': 'Copy link',
    'share.copied': 'Link copied!',
    'share.whatsapp': 'WhatsApp',
    'share.facebook': 'Facebook',
    'share.twitter': 'X (Twitter)',
    'share.linkedin': 'LinkedIn',
    'article.views': 'views',
    'article.shares': 'shares',
    'article.comments': 'Comments',
    'article.add.comment': 'Add a comment...',
    'article.post.comment': 'Post comment',
    'article.login.comment': 'Log in to join the discussion.',
    'forum.subtitle': 'Join the conversation. Connect with other teens and be part of the community.',
    'forum.all': 'All',
    'forum.general': 'General Discussion',
    'forum.general.desc': 'Anything and everything.',
    'forum.school': 'School & Homework',
    'forum.school.desc': 'Help with math, essays, or teacher stories.',
    'forum.gaming': 'Gaming',
    'forum.gaming.desc': 'LoL, CS2, Minecraft, and more.',
    'forum.music': 'Music & Art',
    'forum.music.desc': 'Share your playlists or drawings.',
    'forum.tech': 'Tech & Coding',
    'forum.tech.desc': 'For the geeks and future devs.',
    'forum.new.thread': 'Start a New Thread',
    'forum.new.topic': 'New Topic',
    'forum.topic.title': 'Title',
    'forum.topic.title.placeholder': "What's on your mind?",
    'forum.category': 'Category',
    'forum.create.topic': 'Create Topic',
    'forum.login.post': 'Login to Post',
    'forum.no.topics': 'No topics yet. Start the first thread!',
    'forum.replies': 'replies',
    'forum.back': 'Back to Forum',
    'forum.started.by': 'Started by',
    'forum.reply.count': 'Replies',
    'forum.no.replies': 'No replies yet. Be the first to respond!',
    'forum.write.reply': 'Write a reply...',
    'forum.reply': 'Reply',
    'forum.login.reply': 'Log in to reply.',
    'qa.subtitle': 'Anonymous questions, real answers. Ask anything about school, life, or whatever\'s on your mind.',
    'qa.placeholder': 'Type your question here...',
    'qa.ask': 'Ask',
    'qa.recent': 'Recent Questions',
    'qa.no.questions': 'No questions yet. Be the first to ask!',
    'qa.asked.by': 'Asked by',
    'qa.answered': 'Answered',
    'qa.pending': 'Pending',
    'qa.answer.label': 'Answer:',
    'qa.admin.answer': 'Write an answer...',
    'qa.admin.submit': 'Submit',
    'qa.admin.cancel': 'Cancel',
    'qa.admin.btn': 'Answer as Admin',
    'qa.anonymous': 'Anonymous',
    'qa.delete': 'Delete question',
    'qa.delete.confirm.title': 'Confirm deletion',
    'qa.delete.confirm.message': 'Are you sure you want to delete this question? This action cannot be undone.',
    'qa.delete.confirm.yes': 'Yes, delete',
    'qa.delete.confirm.no': 'Cancel',
    'qa.delete.success': 'Question deleted successfully.',
    'qa.approve': 'Approve',
    'qa.approve.success': 'Question approved.',
    'qa.reject': 'Reject',
    'qa.reject.success': 'Question rejected.',
    'qa.withdraw': 'Withdraw',
    'qa.withdraw.success': 'Your question has been withdrawn.',
    'qa.waiting.approval': 'Your question was submitted and will appear after approval.',
    'qa.status.waiting': 'Awaiting approval',
    'qa.my.pending': 'My question (pending)',
    'qa.delete.forbidden': 'You cannot delete this question because it does not belong to you.',
    'archive.search': 'Search articles...',
    'archive.all': 'All',
    'archive.no.results': 'No articles found.',
    'archive.by': 'by',
    'section.login.write': 'Log in to write',
    'privacy.title': 'Privacy Policy',
    'privacy.updated': 'Last updated:',
    'privacy.s1.title': '1. Introduction',
    'privacy.s1.text': 'Welcome to Diary of a Cool Teen. We respect your privacy and are committed to protecting your personal data. This privacy policy explains what information we collect, how we use it, and what your rights are.',
    'privacy.s2.title': '2. Data we collect',
    'privacy.s2.text': 'We may collect the following types of personal data:',
    'privacy.s2.i1': 'Account information: username, email address, and password (stored encrypted).',
    'privacy.s2.i2': 'Profile information: avatar, information provided through Google sign-in.',
    'privacy.s2.i3': 'Generated content: articles, comments, forum posts, and Q&A questions.',
    'privacy.s2.i4': 'Technical data: IP address, browser type, and session cookies.',
    'privacy.s3.title': '3. How we use data',
    'privacy.s3.text': 'We use collected data for:',
    'privacy.s3.i1': 'Creating and managing your account.',
    'privacy.s3.i2': 'Providing platform features (posts, comments, forum).',
    'privacy.s3.i3': 'Improving user experience.',
    'privacy.s3.i4': 'Ensuring platform security.',
    'privacy.s4.title': '4. Data sharing',
    'privacy.s4.text': 'We do not sell, rent, or share your personal data with third parties for marketing purposes. We may share data only in the following situations:',
    'privacy.s4.i1': 'With service providers (hosting, authentication) that help us operate the platform.',
    'privacy.s4.i2': 'When required by law.',
    'privacy.s5.title': '5. Cookies',
    'privacy.s5.text': 'We use essential cookies for authentication session functionality. These cookies are necessary to keep your session active on the platform.',
    'privacy.s6.title': '6. Data security',
    'privacy.s6.text': 'Passwords are encrypted using bcrypt with 12 salt rounds. Sessions are secure and stored on the server. We use HTTPS protection for data transmission.',
    'privacy.s7.title': '7. Your rights',
    'privacy.s7.text': 'You have the right to:',
    'privacy.s7.i1': 'Request access to your personal data.',
    'privacy.s7.i2': 'Request deletion of your account and associated data.',
    'privacy.s7.i3': 'Withdraw consent for data processing.',
    'privacy.s8.title': '8. Policy changes',
    'privacy.s8.text': 'We may update this policy periodically. We will notify you of significant changes through the platform.',
    'privacy.s9.title': '9. Contact',
    'privacy.s9.text': 'For any privacy-related questions, you can contact us through the platform.',
    'terms.title': 'Terms and Conditions',
    'terms.updated': 'Last updated:',
    'terms.s1.title': '1. Acceptance of terms',
    'terms.s1.text': 'By creating an account on Diary of a Cool Teen, you accept these terms and conditions in full. If you do not agree with these terms, please do not use the platform.',
    'terms.s2.title': '2. Eligibility',
    'terms.s2.text': 'The platform is intended for teenagers and young people. By using the platform, you confirm that you are at least 13 years old or have parental/guardian consent.',
    'terms.s3.title': '3. User account',
    'terms.s3.text': 'By creating an account, you agree to:',
    'terms.s3.i1': 'Provide accurate and up-to-date information.',
    'terms.s3.i2': 'Keep your password confidential.',
    'terms.s3.i3': 'Immediately notify any unauthorized use of your account.',
    'terms.s4.title': '4. User content',
    'terms.s4.text': 'You are responsible for all content you post on the platform. It is forbidden to publish:',
    'terms.s4.i1': 'Illegal, harassing, or discriminatory content.',
    'terms.s4.i2': 'False or misleading information.',
    'terms.s4.i3': 'Content that infringes the copyrights of others.',
    'terms.s4.i4': 'Spam or unauthorized advertising.',
    'terms.s4.i5': 'Explicit or age-inappropriate content.',
    'terms.s5.title': '5. Intellectual property rights',
    'terms.s5.text': 'You retain copyright over your original content. By posting on the platform, you grant us a non-exclusive license to display the content on the platform.',
    'terms.s6.title': '6. Moderation',
    'terms.s6.text': 'We reserve the right to delete any content that violates these terms and to suspend or delete accounts that violate platform rules, without prior notice.',
    'terms.s7.title': '7. Limitation of liability',
    'terms.s7.text': 'The platform is provided "as is." We do not guarantee continuous availability of the service. We are not responsible for data loss or indirect damages.',
    'terms.s8.title': '8. Changes to terms',
    'terms.s8.text': 'We may modify these terms at any time. Continued use of the platform after modification constitutes acceptance of the new terms.',
    'terms.s9.title': '9. Termination',
    'terms.s9.text': 'You may close your account at any time. We reserve the right to terminate access to the platform in case of violation of the terms.',
    'terms.s10.title': '10. Applicable law',
    'terms.s10.text': 'These terms are governed by Romanian law.',
    'nav.profile': 'My Profile',
    'profile.notfound': 'User not found',
    'profile.joined': 'Member since',
    'profile.role.admin': 'Administrator',
    'profile.role.user': 'User',
    'profile.stat.topics': 'Forum Topics',
    'profile.stat.replies': 'Forum Replies',
    'profile.stat.articles': 'Published Articles',
    'profile.published.articles': 'Published Articles',
    'profile.forum.activity': 'Forum Activity',
    'profile.danger.zone': 'Danger Zone',
    'profile.delete.warning': 'Deleting your account is permanent and irreversible. All your personal data will be removed, and your content will be anonymized.',
    'profile.delete.btn': 'Delete Account',
    'profile.delete.confirm.title': 'Confirm Account Deletion',
    'profile.delete.confirm.desc': 'This action is irreversible. Your account and all associated data will be permanently deleted. Generated content will be anonymized.',
    'profile.delete.password.placeholder': 'Enter your password to confirm',
    'profile.delete.confirm.btn': 'Permanently Delete Account',
    'profile.deleted.title': 'Account Deleted',
    'profile.deleted.desc': 'Your account has been successfully deleted.',
    'profile.delete.error': 'Error deleting account',
    'editor.forbidden.title': 'Access Denied',
    'editor.forbidden.desc': 'Only administrators can create articles. If you think you should have access, contact an administrator.',
    'notfound.title': 'Page not found',
    'notfound.text': 'Sorry, the page you are looking for does not exist.',
    'notfound.back': 'Back to home',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms and Conditions',
    'nav.admin': 'Admin Panel',
    'admin.title': 'Administration Panel',
    'admin.forbidden.desc': 'Only administrators have access to the admin panel.',
    'admin.pending': 'pending reports',
    'admin.stat.users': 'Users',
    'admin.stat.posts': 'Articles',
    'admin.stat.comments': 'Comments',
    'admin.stat.reports': 'Active Reports',
    'admin.stat.topics': 'Forum Topics',
    'admin.tab.users': 'Users',
    'admin.tab.content': 'Content',
    'admin.tab.reports': 'Reports',
    'admin.tab.logs': 'Logs',
    'admin.users.title': 'User Management',
    'admin.users.search': 'Search users...',
    'admin.promote': 'Promote',
    'admin.demote': 'Demote',
    'admin.block': 'Block',
    'admin.unblock': 'Unblock',
    'admin.blocked': 'Blocked',
    'admin.role.updated': 'Role updated successfully',
    'admin.user.blocked': 'User blocked successfully',
    'admin.user.unblocked': 'User unblocked successfully',
    'admin.user.deleted': 'User deleted successfully',
    'admin.error': 'Error',
    'admin.no.users': 'No users found.',
    'admin.confirm.delete.user': 'Are you sure you want to delete this user? This action is irreversible.',
    'admin.articles': 'Articles',
    'admin.comments': 'Comments',
    'admin.hidden': 'Hidden',
    'admin.content.updated': 'Content updated',
    'admin.post.deleted': 'Article deleted',
    'admin.comment.deleted': 'Comment deleted',
    'admin.no.posts': 'No articles.',
    'admin.no.comments': 'No comments.',
    'admin.confirm.delete.post': 'Are you sure you want to delete this article?',
    'admin.confirm.delete.comment': 'Are you sure you want to delete this comment?',
    'admin.reports.title': 'Reported Content',
    'admin.report.pending': 'Pending',
    'admin.report.resolved.label': 'Resolved',
    'admin.report.dismissed': 'Dismissed',
    'admin.reported.by': 'Reported by',
    'admin.resolve': 'Resolve',
    'admin.dismiss': 'Dismiss',
    'admin.report.resolved': 'Report resolved',
    'admin.no.reports': 'No reports.',
    'admin.logs.title': 'Activity Logs',
    'admin.no.logs': 'No activity logs.',
    'admin.block.title': 'Block user',
    'admin.block.desc': 'Blocked users cannot post, comment, or log in.',
    'admin.block.reason': 'Block reason',
    'admin.block.reason.placeholder': 'Enter the reason for blocking...',
    'admin.block.until': 'Blocked until (optional)',
    'admin.block.permanent.note': 'Leave empty for permanent block.',
    'admin.gdpr.title': 'GDPR Compliance',
    'admin.gdpr.retention.title': 'Data Retention Policy',
    'admin.gdpr.retention.text': 'User data is stored for the duration of the account. Upon account deletion, personal data is anonymized or completely deleted per user preference. Session cookies expire after 30 days.',
    'admin.gdpr.rights.title': 'User Rights',
    'admin.gdpr.rights.access': 'Right to access personal data',
    'admin.gdpr.rights.rectification': 'Right to rectification of data',
    'admin.gdpr.rights.erasure': 'Right to erasure (right to be forgotten)',
    'admin.gdpr.rights.portability': 'Right to data portability (JSON export)',
    'admin.gdpr.rights.object': 'Right to object to data processing',
    'admin.gdpr.export.title': 'User Data Export',
    'admin.gdpr.export.text': 'Users can export all their personal data in JSON format from their profile page.',
    'admin.gdpr.export.note': 'Endpoint: GET /api/auth/export-data (requires authentication)',
    'report.btn': 'Report',
    'report.reason.placeholder': 'Describe why you are reporting...',
    'report.submitted': 'Report submitted successfully.',
    'profile.export.btn': 'Export my data',
    'profile.export.desc': 'Download all your personal data in JSON format (GDPR compliant).',
    'forum.topic.delete': 'Delete thread',
    'forum.topic.delete.confirm.title': 'Delete thread',
    'forum.topic.delete.confirm.desc': 'Are you sure? All replies in this thread will be permanently deleted.',
    'report.title': 'Report content',
    'report.desc': 'Describe why you are reporting this content. Admins will be notified.',
    'report.confirm': 'Submit report',
    'nav.notifications': 'Notifications',
    'nav.notif.markall': 'Mark all read',
    'nav.notif.empty': 'No new notifications.',
    'qa.login.required': 'You must be logged in to ask a question.',
    'archive.restricted.title': 'Restricted Access',
    'archive.restricted.desc': 'The Archive section is available for administrators only.',
    'profile.edit.title': 'Edit Profile',
    'profile.edit.username': 'New username',
    'profile.edit.username.placeholder': 'Enter new username...',
    'profile.edit.username.hint': 'Letters, numbers and underscore (_) only. Between 3-30 characters.',
    'profile.edit.current.password': 'Current password',
    'profile.edit.current.password.placeholder': 'Your current password...',
    'profile.edit.new.password': 'New password',
    'profile.edit.new.password.placeholder': 'New password (min. 6 characters)...',
    'profile.edit.confirm.password': 'Confirm new password',
    'profile.edit.confirm.password.placeholder': 'Repeat new password...',
    'profile.edit.save': 'Save changes',
    'profile.edit.success': 'Profile updated successfully!',
    'profile.edit.error': 'Error updating profile',
    'profile.edit.passwords.mismatch': 'New passwords do not match',
    'profile.edit.no.changes': 'No changes detected',
    'profile.edit.google.note': 'Your account is connected via Google. You cannot change your password directly.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.life': 'Vida de Estudiante',
    'nav.hobbies': 'Pasatiempos',
    'nav.advice': 'Relaciones',
    'nav.forum': 'Foro',
    'nav.qa': 'Preguntas',
    'nav.archive': 'Archivo',
    'nav.login': 'Iniciar sesión',
    'nav.logout': 'Cerrar sesión',
    'nav.darkmode': 'Modo oscuro',
    'nav.lightmode': 'Modo claro',
    'nav.language': 'Idioma',
    'hero.title': 'Diario de un adolescente genial',
    'hero.subtitle': 'Un lugar seguro para tus pensamientos, nuevos amigos y consejos reales.',
    'latest.articles': 'Últimos artículos',
    'btn.readmore': 'Leer más',
    'btn.create': 'Escribir un artículo',
    'btn.back': 'Atrás',
    'btn.cancel': 'Cancelar',
    'btn.delete': 'Eliminar',
    'btn.like': 'Me gusta',
    'btn.submit': 'Enviar',
    'btn.save': 'Guardar',
    'auth.login.title': 'Iniciar sesión',
    'auth.register.title': 'Crear cuenta',
    'auth.join': '¡Únete a la comunidad!',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.username': 'Nombre de usuario',
    'auth.password.min': 'Mín. 6 caracteres',
    'auth.accept.terms': 'Acepto los',
    'auth.terms.link': 'Términos y Condiciones',
    'auth.and': 'y',
    'auth.privacy.link': 'Política de Privacidad',
    'auth.google': 'Iniciar sesión con Google',
    'auth.login.prompt': 'Inicia sesión para participar',
    'no.posts': 'Aún no hay publicaciones.',
    'no.posts.cta': 'Empieza a escribir tus propios artículos ahora.',
    'create.post.title': 'Título del artículo',
    'create.post.content': '¿Sobre qué quieres escribir hoy?',
    'create.post.submit': 'Publicar',
    'category.liceu': 'Vida Estudiantil',
    'category.hobby': 'Pasatiempos y Pasiones',
    'category.sfaturi': 'Relaciones',
    'category.general': 'General',
    'editor.title': 'Escribir un artículo nuevo',
    'editor.title.edit': 'Editar artículo',
    'editor.title.placeholder': 'Un título cautivador para tu artículo...',
    'editor.section': 'Sección',
    'editor.content.placeholder': 'Empieza a escribir aquí...',
    'editor.published': '¡Artículo publicado!',
    'editor.updated': '¡Artículo actualizado!',
    'editor.redirect': 'Serás redirigido en unos segundos...',
    'btn.edit': 'Editar',
    'btn.update': 'Actualizar',
    'share.title': 'Compartir artículo',
    'share.copy': 'Copiar enlace',
    'share.copied': '¡Enlace copiado!',
    'share.whatsapp': 'WhatsApp',
    'share.facebook': 'Facebook',
    'share.twitter': 'X (Twitter)',
    'share.linkedin': 'LinkedIn',
    'article.views': 'vistas',
    'article.shares': 'compartidos',
    'article.comments': 'Comentarios',
    'article.add.comment': 'Añade un comentario...',
    'article.post.comment': 'Publicar comentario',
    'article.login.comment': 'Inicia sesión para unirte a la discusión.',
    'forum.subtitle': 'Únete a la conversación. Conéctate con otros adolescentes.',
    'forum.all': 'Todos',
    'forum.general': 'Discusión General',
    'forum.general.desc': 'Todo y cualquier cosa.',
    'forum.school': 'Escuela y Tareas',
    'forum.school.desc': 'Ayuda con matemáticas, ensayos o historias de profesores.',
    'forum.gaming': 'Gaming',
    'forum.gaming.desc': 'LoL, CS2, Minecraft y más.',
    'forum.music': 'Música y Arte',
    'forum.music.desc': 'Comparte tus playlists o dibujos.',
    'forum.tech': 'Tecnología y Código',
    'forum.tech.desc': 'Para los geeks y futuros desarrolladores.',
    'forum.new.thread': 'Iniciar un nuevo hilo',
    'forum.new.topic': 'Nuevo tema',
    'forum.topic.title': 'Título',
    'forum.topic.title.placeholder': '¿Qué tienes en mente?',
    'forum.category': 'Categoría',
    'forum.create.topic': 'Crear tema',
    'forum.login.post': 'Inicia sesión para publicar',
    'forum.no.topics': 'Aún no hay temas. ¡Inicia el primer hilo!',
    'forum.replies': 'respuestas',
    'forum.back': 'Volver al Foro',
    'forum.started.by': 'Iniciado por',
    'forum.reply.count': 'Respuestas',
    'forum.no.replies': '¡No hay respuestas aún. Sé el primero en responder!',
    'forum.write.reply': 'Escribe una respuesta...',
    'forum.reply': 'Responder',
    'forum.login.reply': 'Inicia sesión para responder.',
    'qa.subtitle': 'Preguntas anónimas, respuestas reales. Pregunta lo que quieras.',
    'qa.placeholder': 'Escribe tu pregunta aquí...',
    'qa.ask': 'Preguntar',
    'qa.recent': 'Preguntas recientes',
    'qa.no.questions': '¡No hay preguntas aún. Sé el primero en preguntar!',
    'qa.asked.by': 'Preguntado por',
    'qa.answered': 'Respondido',
    'qa.pending': 'Pendiente',
    'qa.answer.label': 'Respuesta:',
    'qa.admin.answer': 'Escribe una respuesta...',
    'qa.admin.submit': 'Enviar',
    'qa.admin.cancel': 'Cancelar',
    'qa.admin.btn': 'Responder como Admin',
    'qa.anonymous': 'Anónimo',
    'qa.delete': 'Eliminar pregunta',
    'qa.delete.confirm.title': 'Confirmar eliminación',
    'qa.delete.confirm.message': '¿Estás seguro de que quieres eliminar esta pregunta? Esta acción no se puede deshacer.',
    'qa.delete.confirm.yes': 'Sí, eliminar',
    'qa.delete.confirm.no': 'Cancelar',
    'qa.delete.success': 'Pregunta eliminada con éxito.',
    'qa.approve': 'Aprobar',
    'qa.approve.success': 'Pregunta aprobada.',
    'qa.reject': 'Rechazar',
    'qa.reject.success': 'Pregunta rechazada.',
    'qa.withdraw': 'Retirar',
    'qa.withdraw.success': 'Tu pregunta ha sido retirada.',
    'qa.waiting.approval': 'Tu pregunta fue enviada y aparecerá tras la aprobación.',
    'qa.status.waiting': 'Esperando aprobación',
    'qa.my.pending': 'Mi pregunta (pendiente)',
    'qa.delete.forbidden': 'No puedes eliminar esta pregunta porque no te pertenece.',
    'archive.search': 'Buscar artículos...',
    'archive.all': 'Todos',
    'archive.no.results': 'No se encontraron artículos.',
    'archive.by': 'por',
    'section.login.write': 'Inicia sesión para escribir',
    'privacy.title': 'Política de Privacidad',
    'privacy.updated': 'Última actualización:',
    'privacy.s1.title': '1. Introducción',
    'privacy.s1.text': 'Bienvenido a Diario de un adolescente genial. Respetamos tu privacidad y nos comprometemos a proteger tus datos personales.',
    'privacy.s2.title': '2. Datos que recopilamos',
    'privacy.s2.text': 'Podemos recopilar los siguientes tipos de datos personales:',
    'privacy.s2.i1': 'Información de cuenta: nombre de usuario, correo electrónico y contraseña (almacenada encriptada).',
    'privacy.s2.i2': 'Información de perfil: avatar, información proporcionada a través de Google.',
    'privacy.s2.i3': 'Contenido generado: artículos, comentarios, publicaciones del foro y preguntas.',
    'privacy.s2.i4': 'Datos técnicos: dirección IP, tipo de navegador y cookies de sesión.',
    'privacy.s3.title': '3. Cómo usamos los datos',
    'privacy.s3.text': 'Usamos los datos recopilados para:',
    'privacy.s3.i1': 'Crear y gestionar tu cuenta.',
    'privacy.s3.i2': 'Proporcionar las funcionalidades de la plataforma.',
    'privacy.s3.i3': 'Mejorar la experiencia del usuario.',
    'privacy.s3.i4': 'Garantizar la seguridad de la plataforma.',
    'privacy.s4.title': '4. Compartir datos',
    'privacy.s4.text': 'No vendemos ni compartimos tus datos personales con fines de marketing.',
    'privacy.s4.i1': 'Con proveedores de servicios que nos ayudan a operar la plataforma.',
    'privacy.s4.i2': 'Cuando lo exija la ley.',
    'privacy.s5.title': '5. Cookies',
    'privacy.s5.text': 'Usamos cookies esenciales para la funcionalidad de autenticación.',
    'privacy.s6.title': '6. Seguridad de datos',
    'privacy.s6.text': 'Las contraseñas están encriptadas con bcrypt. Las sesiones son seguras.',
    'privacy.s7.title': '7. Tus derechos',
    'privacy.s7.text': 'Tienes derecho a:',
    'privacy.s7.i1': 'Solicitar acceso a tus datos personales.',
    'privacy.s7.i2': 'Solicitar la eliminación de tu cuenta.',
    'privacy.s7.i3': 'Retirar el consentimiento para el procesamiento de datos.',
    'privacy.s8.title': '8. Cambios en la política',
    'privacy.s8.text': 'Podemos actualizar esta política periódicamente.',
    'privacy.s9.title': '9. Contacto',
    'privacy.s9.text': 'Para preguntas sobre privacidad, contáctanos a través de la plataforma.',
    'terms.title': 'Términos y Condiciones',
    'terms.updated': 'Última actualización:',
    'terms.s1.title': '1. Aceptación de términos',
    'terms.s1.text': 'Al crear una cuenta, aceptas estos términos y condiciones.',
    'terms.s2.title': '2. Elegibilidad',
    'terms.s2.text': 'La plataforma está destinada a adolescentes. Confirmas que tienes al menos 13 años.',
    'terms.s3.title': '3. Cuenta de usuario',
    'terms.s3.text': 'Al crear una cuenta, te comprometes a:',
    'terms.s3.i1': 'Proporcionar información correcta y actualizada.',
    'terms.s3.i2': 'Mantener la confidencialidad de tu contraseña.',
    'terms.s3.i3': 'Notificar cualquier uso no autorizado de tu cuenta.',
    'terms.s4.title': '4. Contenido del usuario',
    'terms.s4.text': 'Eres responsable de todo el contenido que publiques. Está prohibido publicar:',
    'terms.s4.i1': 'Contenido ilegal, acosador o discriminatorio.',
    'terms.s4.i2': 'Información falsa o engañosa.',
    'terms.s4.i3': 'Contenido que infrinja derechos de autor.',
    'terms.s4.i4': 'Spam o publicidad no autorizada.',
    'terms.s4.i5': 'Contenido explícito o inapropiado para menores.',
    'terms.s5.title': '5. Propiedad intelectual',
    'terms.s5.text': 'Conservas los derechos de autor sobre tu contenido original.',
    'terms.s6.title': '6. Moderación',
    'terms.s6.text': 'Nos reservamos el derecho de eliminar contenido que viole estos términos.',
    'terms.s7.title': '7. Limitación de responsabilidad',
    'terms.s7.text': 'La plataforma se proporciona "tal cual".',
    'terms.s8.title': '8. Cambios en los términos',
    'terms.s8.text': 'Podemos modificar estos términos en cualquier momento.',
    'terms.s9.title': '9. Terminación',
    'terms.s9.text': 'Puedes cerrar tu cuenta en cualquier momento.',
    'terms.s10.title': '10. Ley aplicable',
    'terms.s10.text': 'Estos términos se rigen por la legislación rumana.',
    'nav.profile': 'Mi Perfil',
    'profile.notfound': 'Usuario no encontrado',
    'profile.joined': 'Miembro desde',
    'profile.role.admin': 'Administrador',
    'profile.role.user': 'Usuario',
    'profile.stat.topics': 'Temas del foro',
    'profile.stat.replies': 'Respuestas del foro',
    'profile.stat.articles': 'Artículos publicados',
    'profile.published.articles': 'Artículos publicados',
    'profile.forum.activity': 'Actividad en el foro',
    'profile.danger.zone': 'Zona de peligro',
    'profile.delete.warning': 'Eliminar tu cuenta es permanente e irreversible. Todos tus datos personales serán eliminados y tu contenido será anonimizado.',
    'profile.delete.btn': 'Eliminar cuenta',
    'profile.delete.confirm.title': 'Confirmar eliminación de cuenta',
    'profile.delete.confirm.desc': 'Esta acción es irreversible. Tu cuenta y todos los datos asociados serán eliminados permanentemente.',
    'profile.delete.password.placeholder': 'Ingresa tu contraseña para confirmar',
    'profile.delete.confirm.btn': 'Eliminar cuenta permanentemente',
    'profile.deleted.title': 'Cuenta eliminada',
    'profile.deleted.desc': 'Tu cuenta ha sido eliminada exitosamente.',
    'profile.delete.error': 'Error al eliminar la cuenta',
    'editor.forbidden.title': 'Acceso denegado',
    'editor.forbidden.desc': 'Solo los administradores pueden crear artículos.',
    'notfound.title': 'Página no encontrada',
    'notfound.text': 'Lo sentimos, la página que buscas no existe.',
    'notfound.back': 'Volver al inicio',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos y Condiciones',
    'nav.admin': 'Panel Admin',
    'admin.title': 'Panel de Administración',
    'admin.forbidden.desc': 'Solo los administradores tienen acceso al panel de administración.',
    'admin.pending': 'reportes pendientes',
    'admin.stat.users': 'Usuarios',
    'admin.stat.posts': 'Artículos',
    'admin.stat.comments': 'Comentarios',
    'admin.stat.reports': 'Reportes activos',
    'admin.stat.topics': 'Temas del foro',
    'admin.tab.users': 'Usuarios',
    'admin.tab.content': 'Contenido',
    'admin.tab.reports': 'Reportes',
    'admin.tab.logs': 'Registros',
    'admin.users.title': 'Gestión de usuarios',
    'admin.users.search': 'Buscar usuarios...',
    'admin.promote': 'Promover',
    'admin.demote': 'Degradar',
    'admin.block': 'Bloquear',
    'admin.unblock': 'Desbloquear',
    'admin.blocked': 'Bloqueado',
    'admin.role.updated': 'Rol actualizado exitosamente',
    'admin.user.blocked': 'Usuario bloqueado exitosamente',
    'admin.user.unblocked': 'Usuario desbloqueado exitosamente',
    'admin.user.deleted': 'Usuario eliminado exitosamente',
    'admin.error': 'Error',
    'admin.no.users': 'No se encontraron usuarios.',
    'admin.confirm.delete.user': '¿Estás seguro de que quieres eliminar este usuario? Esta acción es irreversible.',
    'admin.articles': 'Artículos',
    'admin.comments': 'Comentarios',
    'admin.hidden': 'Oculto',
    'admin.content.updated': 'Contenido actualizado',
    'admin.post.deleted': 'Artículo eliminado',
    'admin.comment.deleted': 'Comentario eliminado',
    'admin.no.posts': 'No hay artículos.',
    'admin.no.comments': 'No hay comentarios.',
    'admin.confirm.delete.post': '¿Estás seguro de que quieres eliminar este artículo?',
    'admin.confirm.delete.comment': '¿Estás seguro de que quieres eliminar este comentario?',
    'admin.reports.title': 'Contenido reportado',
    'admin.report.pending': 'Pendiente',
    'admin.report.resolved.label': 'Resuelto',
    'admin.report.dismissed': 'Descartado',
    'admin.reported.by': 'Reportado por',
    'admin.resolve': 'Resolver',
    'admin.dismiss': 'Descartar',
    'admin.report.resolved': 'Reporte resuelto',
    'admin.no.reports': 'No hay reportes.',
    'admin.logs.title': 'Registros de actividad',
    'admin.no.logs': 'No hay registros de actividad.',
    'admin.block.title': 'Bloquear usuario',
    'admin.block.desc': 'Los usuarios bloqueados no podrán publicar, comentar o iniciar sesión.',
    'admin.block.reason': 'Motivo del bloqueo',
    'admin.block.reason.placeholder': 'Ingresa el motivo del bloqueo...',
    'admin.block.until': 'Bloqueado hasta (opcional)',
    'admin.block.permanent.note': 'Dejar vacío para bloqueo permanente.',
    'admin.gdpr.title': 'Cumplimiento GDPR',
    'admin.gdpr.retention.title': 'Política de retención de datos',
    'admin.gdpr.retention.text': 'Los datos de los usuarios se almacenan durante la existencia de la cuenta. Al eliminar la cuenta, los datos personales se anonimizan o eliminan completamente según la preferencia del usuario.',
    'admin.gdpr.rights.title': 'Derechos del usuario',
    'admin.gdpr.rights.access': 'Derecho de acceso a datos personales',
    'admin.gdpr.rights.rectification': 'Derecho a la rectificación de datos',
    'admin.gdpr.rights.erasure': 'Derecho al olvido (eliminación de datos)',
    'admin.gdpr.rights.portability': 'Derecho a la portabilidad de datos (exportación JSON)',
    'admin.gdpr.rights.object': 'Derecho de oposición al procesamiento de datos',
    'admin.gdpr.export.title': 'Exportar datos de usuario',
    'admin.gdpr.export.text': 'Los usuarios pueden exportar todos sus datos personales en formato JSON desde su página de perfil.',
    'admin.gdpr.export.note': 'Endpoint: GET /api/auth/export-data (requiere autenticación)',
    'report.btn': 'Reportar',
    'report.reason.placeholder': 'Describe por qué estás reportando...',
    'report.submitted': 'Reporte enviado exitosamente.',
    'profile.export.btn': 'Exportar mis datos',
    'profile.export.desc': 'Descarga todos tus datos personales en formato JSON (conforme a GDPR).',
    'forum.topic.delete': 'Eliminar hilo',
    'forum.topic.delete.confirm.title': 'Eliminar hilo',
    'forum.topic.delete.confirm.desc': '¿Estás seguro? Todas las respuestas de este hilo serán eliminadas permanentemente.',
    'report.title': 'Reportar contenido',
    'report.desc': 'Describe por qué reportas este contenido. Los administradores serán notificados.',
    'report.confirm': 'Enviar reporte',
    'nav.notifications': 'Notificaciones',
    'nav.notif.markall': 'Marcar todo leído',
    'nav.notif.empty': 'No hay notificaciones nuevas.',
    'qa.login.required': 'Debes iniciar sesión para hacer una pregunta.',
    'archive.restricted.title': 'Acceso restringido',
    'archive.restricted.desc': 'La sección de Archivo solo está disponible para administradores.',
    'profile.edit.title': 'Editar perfil',
    'profile.edit.username': 'Nuevo nombre de usuario',
    'profile.edit.username.placeholder': 'Introduce el nuevo nombre de usuario...',
    'profile.edit.username.hint': 'Solo letras, números y guión bajo (_). Entre 3-30 caracteres.',
    'profile.edit.current.password': 'Contraseña actual',
    'profile.edit.current.password.placeholder': 'Tu contraseña actual...',
    'profile.edit.new.password': 'Nueva contraseña',
    'profile.edit.new.password.placeholder': 'Nueva contraseña (mín. 6 caracteres)...',
    'profile.edit.confirm.password': 'Confirmar nueva contraseña',
    'profile.edit.confirm.password.placeholder': 'Repite la nueva contraseña...',
    'profile.edit.save': 'Guardar cambios',
    'profile.edit.success': '¡Perfil actualizado con éxito!',
    'profile.edit.error': 'Error al actualizar el perfil',
    'profile.edit.passwords.mismatch': 'Las nuevas contraseñas no coinciden',
    'profile.edit.no.changes': 'No se detectaron cambios',
    'profile.edit.google.note': 'Tu cuenta está conectada a través de Google. No puedes cambiar la contraseña directamente.',
  },
  fr: {
    'nav.home': 'Accueil', 'nav.life': 'Vie Lycéenne', 'nav.hobbies': 'Loisirs', 'nav.advice': 'Relations', 'nav.forum': 'Forum', 'nav.qa': 'Questions', 'nav.archive': 'Archives', 'nav.login': 'Connexion', 'nav.logout': 'Déconnexion', 'nav.darkmode': 'Mode sombre', 'nav.lightmode': 'Mode clair', 'nav.language': 'Langue',
    'hero.title': 'Journal d\'un ado cool', 'hero.subtitle': 'Un endroit sûr pour tes pensées, de nouveaux amis et de vrais conseils.', 'latest.articles': 'Derniers articles', 'btn.readmore': 'Lire la suite', 'btn.create': 'Écrire un article', 'btn.back': 'Retour', 'btn.cancel': 'Annuler', 'btn.delete': 'Supprimer', 'btn.like': 'J\'aime', 'btn.submit': 'Envoyer', 'btn.save': 'Sauvegarder',
    'auth.login.title': 'Se connecter', 'auth.register.title': 'Créer un compte', 'auth.join': 'Rejoins la communauté !', 'auth.email': 'Email', 'auth.password': 'Mot de passe', 'auth.username': 'Nom d\'utilisateur', 'auth.password.min': 'Min. 6 caractères', 'auth.accept.terms': 'J\'accepte les', 'auth.terms.link': 'Conditions Générales', 'auth.and': 'et', 'auth.privacy.link': 'Politique de Confidentialité', 'auth.google': 'Se connecter avec Google', 'auth.login.prompt': 'Connecte-toi pour participer',
    'no.posts': 'Pas encore de publications.', 'no.posts.cta': 'Commence à écrire tes propres articles maintenant.', 'create.post.title': 'Titre de l\'article', 'create.post.content': 'De quoi veux-tu écrire aujourd\'hui ?', 'create.post.submit': 'Publier',
    'category.liceu': 'Vie Lycéenne', 'category.hobby': 'Loisirs & Passions', 'category.sfaturi': 'Relations', 'category.general': 'Général',
    'editor.title': 'Écrire un nouvel article', 'editor.title.placeholder': 'Un titre captivant...', 'editor.section': 'Section', 'editor.content.placeholder': 'Commence à écrire ici...', 'editor.published': 'Article publié !', 'editor.redirect': 'Tu seras redirigé dans quelques secondes...',
    'article.comments': 'Commentaires', 'article.add.comment': 'Ajouter un commentaire...', 'article.post.comment': 'Poster le commentaire', 'article.login.comment': 'Connecte-toi pour participer à la discussion.',
    'forum.subtitle': 'Rejoins la conversation. Connecte-toi avec d\'autres ados.', 'forum.all': 'Tous', 'forum.general': 'Discussion Générale', 'forum.general.desc': 'Tout et n\'importe quoi.', 'forum.school': 'École & Devoirs', 'forum.school.desc': 'Aide en maths, dissertations ou histoires de profs.', 'forum.gaming': 'Gaming', 'forum.gaming.desc': 'LoL, CS2, Minecraft et plus.', 'forum.music': 'Musique & Art', 'forum.music.desc': 'Partage tes playlists ou dessins.', 'forum.tech': 'Tech & Code', 'forum.tech.desc': 'Pour les geeks et futurs devs.',
    'forum.new.thread': 'Nouveau sujet', 'forum.new.topic': 'Nouveau sujet', 'forum.topic.title': 'Titre', 'forum.topic.title.placeholder': 'Qu\'est-ce qui te préoccupe ?', 'forum.category': 'Catégorie', 'forum.create.topic': 'Créer le sujet', 'forum.login.post': 'Connecte-toi pour poster', 'forum.no.topics': 'Pas encore de sujets. Lance le premier !', 'forum.replies': 'réponses',
    'forum.back': 'Retour au Forum', 'forum.started.by': 'Lancé par', 'forum.reply.count': 'Réponses', 'forum.no.replies': 'Pas encore de réponses. Sois le premier !', 'forum.write.reply': 'Écrire une réponse...', 'forum.reply': 'Répondre', 'forum.login.reply': 'Connecte-toi pour répondre.',
    'qa.subtitle': 'Questions anonymes, vraies réponses.', 'qa.placeholder': 'Écris ta question ici...', 'qa.ask': 'Demander', 'qa.recent': 'Questions récentes', 'qa.no.questions': 'Pas encore de questions. Sois le premier !', 'qa.asked.by': 'Posée par', 'qa.answered': 'Répondu', 'qa.pending': 'En attente', 'qa.answer.label': 'Réponse :', 'qa.admin.answer': 'Écrire une réponse...', 'qa.admin.submit': 'Envoyer', 'qa.admin.cancel': 'Annuler', 'qa.admin.btn': 'Répondre en tant qu\'Admin',
    'archive.search': 'Rechercher des articles...', 'archive.all': 'Tous', 'archive.no.results': 'Aucun article trouvé.', 'archive.by': 'par', 'section.login.write': 'Connecte-toi pour écrire',
    'privacy.title': 'Politique de Confidentialité', 'privacy.updated': 'Dernière mise à jour :', 'privacy.s1.title': '1. Introduction', 'privacy.s1.text': 'Bienvenue. Nous respectons ta vie privée.', 'privacy.s2.title': '2. Données collectées', 'privacy.s2.text': 'Nous pouvons collecter :', 'privacy.s2.i1': 'Informations de compte.', 'privacy.s2.i2': 'Informations de profil.', 'privacy.s2.i3': 'Contenu généré.', 'privacy.s2.i4': 'Données techniques.', 'privacy.s3.title': '3. Utilisation des données', 'privacy.s3.text': 'Nous utilisons les données pour :', 'privacy.s3.i1': 'Gérer ton compte.', 'privacy.s3.i2': 'Fournir les fonctionnalités.', 'privacy.s3.i3': 'Améliorer l\'expérience.', 'privacy.s3.i4': 'Assurer la sécurité.', 'privacy.s4.title': '4. Partage des données', 'privacy.s4.text': 'Nous ne vendons pas tes données.', 'privacy.s4.i1': 'Avec nos fournisseurs de services.', 'privacy.s4.i2': 'Si requis par la loi.', 'privacy.s5.title': '5. Cookies', 'privacy.s5.text': 'Nous utilisons des cookies essentiels.', 'privacy.s6.title': '6. Sécurité', 'privacy.s6.text': 'Les mots de passe sont chiffrés.', 'privacy.s7.title': '7. Tes droits', 'privacy.s7.text': 'Tu as le droit de :', 'privacy.s7.i1': 'Accéder à tes données.', 'privacy.s7.i2': 'Supprimer ton compte.', 'privacy.s7.i3': 'Retirer ton consentement.', 'privacy.s8.title': '8. Modifications', 'privacy.s8.text': 'Nous pouvons mettre à jour cette politique.', 'privacy.s9.title': '9. Contact', 'privacy.s9.text': 'Contacte-nous via la plateforme.',
    'terms.title': 'Conditions Générales', 'terms.updated': 'Dernière mise à jour :', 'terms.s1.title': '1. Acceptation', 'terms.s1.text': 'En créant un compte, tu acceptes ces conditions.', 'terms.s2.title': '2. Éligibilité', 'terms.s2.text': 'Tu dois avoir au moins 13 ans.', 'terms.s3.title': '3. Compte', 'terms.s3.text': 'Tu t\'engages à :', 'terms.s3.i1': 'Fournir des informations exactes.', 'terms.s3.i2': 'Garder ton mot de passe confidentiel.', 'terms.s3.i3': 'Signaler tout usage non autorisé.', 'terms.s4.title': '4. Contenu', 'terms.s4.text': 'Tu es responsable de ton contenu. Il est interdit de publier :', 'terms.s4.i1': 'Contenu illégal ou discriminatoire.', 'terms.s4.i2': 'Informations fausses.', 'terms.s4.i3': 'Contenu violant les droits d\'auteur.', 'terms.s4.i4': 'Spam ou publicité.', 'terms.s4.i5': 'Contenu inapproprié pour les mineurs.', 'terms.s5.title': '5. Propriété intellectuelle', 'terms.s5.text': 'Tu conserves tes droits d\'auteur.', 'terms.s6.title': '6. Modération', 'terms.s6.text': 'Nous pouvons supprimer du contenu.', 'terms.s7.title': '7. Responsabilité', 'terms.s7.text': 'La plateforme est fournie « telle quelle ».', 'terms.s8.title': '8. Modifications', 'terms.s8.text': 'Nous pouvons modifier ces conditions.', 'terms.s9.title': '9. Résiliation', 'terms.s9.text': 'Tu peux fermer ton compte à tout moment.', 'terms.s10.title': '10. Loi applicable', 'terms.s10.text': 'Loi roumaine applicable.',
    'notfound.title': 'Page non trouvée', 'notfound.text': 'Désolé, cette page n\'existe pas.', 'notfound.back': 'Retour à l\'accueil', 'footer.rights': 'Tous droits réservés.', 'footer.privacy': 'Politique de Confidentialité', 'footer.terms': 'Conditions Générales',
  },
  de: {
    'nav.home': 'Startseite', 'nav.life': 'Schulleben', 'nav.hobbies': 'Hobbys', 'nav.advice': 'Beziehungen', 'nav.forum': 'Forum', 'nav.qa': 'Fragen', 'nav.archive': 'Archiv', 'nav.login': 'Anmelden', 'nav.logout': 'Abmelden', 'nav.darkmode': 'Dunkelmodus', 'nav.lightmode': 'Hellmodus', 'nav.language': 'Sprache',
    'hero.title': 'Tagebuch eines coolen Teenagers', 'hero.subtitle': 'Ein sicherer Ort für deine Gedanken, neue Freunde und echte Tipps.', 'latest.articles': 'Neueste Artikel', 'btn.readmore': 'Mehr lesen', 'btn.create': 'Artikel schreiben', 'btn.back': 'Zurück', 'btn.cancel': 'Abbrechen', 'btn.delete': 'Löschen', 'btn.like': 'Gefällt mir', 'btn.submit': 'Absenden', 'btn.save': 'Speichern',
    'auth.login.title': 'Anmelden', 'auth.register.title': 'Konto erstellen', 'auth.join': 'Tritt der Community bei!', 'auth.email': 'E-Mail', 'auth.password': 'Passwort', 'auth.username': 'Benutzername', 'auth.password.min': 'Min. 6 Zeichen', 'auth.accept.terms': 'Ich akzeptiere die', 'auth.terms.link': 'AGB', 'auth.and': 'und', 'auth.privacy.link': 'Datenschutzrichtlinie', 'auth.google': 'Mit Google anmelden', 'auth.login.prompt': 'Melde dich an, um teilzunehmen',
    'no.posts': 'Noch keine Beiträge.', 'no.posts.cta': 'Schreibe jetzt deine eigenen Artikel.', 'create.post.title': 'Artikeltitel', 'create.post.content': 'Worüber möchtest du heute schreiben?', 'create.post.submit': 'Veröffentlichen',
    'category.liceu': 'Schulleben', 'category.hobby': 'Hobbys & Leidenschaften', 'category.sfaturi': 'Beziehungen', 'category.general': 'Allgemein',
    'editor.title': 'Neuen Artikel schreiben', 'editor.title.placeholder': 'Ein fesselnder Titel...', 'editor.section': 'Bereich', 'editor.content.placeholder': 'Hier schreiben...', 'editor.published': 'Artikel veröffentlicht!', 'editor.redirect': 'Du wirst in wenigen Sekunden weitergeleitet...',
    'article.comments': 'Kommentare', 'article.add.comment': 'Kommentar hinzufügen...', 'article.post.comment': 'Kommentar posten', 'article.login.comment': 'Melde dich an, um an der Diskussion teilzunehmen.',
    'forum.subtitle': 'Nimm an der Unterhaltung teil.', 'forum.all': 'Alle', 'forum.general': 'Allgemeine Diskussion', 'forum.general.desc': 'Alles und jedes.', 'forum.school': 'Schule & Hausaufgaben', 'forum.school.desc': 'Hilfe bei Mathe, Aufsätzen oder Lehrergeschichten.', 'forum.gaming': 'Gaming', 'forum.gaming.desc': 'LoL, CS2, Minecraft und mehr.', 'forum.music': 'Musik & Kunst', 'forum.music.desc': 'Teile deine Playlists oder Zeichnungen.', 'forum.tech': 'Tech & Code', 'forum.tech.desc': 'Für Geeks und zukünftige Entwickler.',
    'forum.new.thread': 'Neues Thema starten', 'forum.new.topic': 'Neues Thema', 'forum.topic.title': 'Titel', 'forum.topic.title.placeholder': 'Was beschäftigt dich?', 'forum.category': 'Kategorie', 'forum.create.topic': 'Thema erstellen', 'forum.login.post': 'Anmelden zum Posten', 'forum.no.topics': 'Noch keine Themen. Starte den ersten!', 'forum.replies': 'Antworten',
    'forum.back': 'Zurück zum Forum', 'forum.started.by': 'Gestartet von', 'forum.reply.count': 'Antworten', 'forum.no.replies': 'Noch keine Antworten. Sei der Erste!', 'forum.write.reply': 'Antwort schreiben...', 'forum.reply': 'Antworten', 'forum.login.reply': 'Anmelden zum Antworten.',
    'qa.subtitle': 'Anonyme Fragen, echte Antworten.', 'qa.placeholder': 'Schreib deine Frage hier...', 'qa.ask': 'Fragen', 'qa.recent': 'Neueste Fragen', 'qa.no.questions': 'Noch keine Fragen. Sei der Erste!', 'qa.asked.by': 'Gefragt von', 'qa.answered': 'Beantwortet', 'qa.pending': 'Ausstehend', 'qa.answer.label': 'Antwort:', 'qa.admin.answer': 'Antwort schreiben...', 'qa.admin.submit': 'Absenden', 'qa.admin.cancel': 'Abbrechen', 'qa.admin.btn': 'Als Admin antworten',
    'archive.search': 'Artikel suchen...', 'archive.all': 'Alle', 'archive.no.results': 'Keine Artikel gefunden.', 'archive.by': 'von', 'section.login.write': 'Anmelden zum Schreiben',
    'privacy.title': 'Datenschutzrichtlinie', 'privacy.updated': 'Letzte Aktualisierung:', 'privacy.s1.title': '1. Einführung', 'privacy.s1.text': 'Willkommen. Wir respektieren deine Privatsphäre.', 'privacy.s2.title': '2. Erhobene Daten', 'privacy.s2.text': 'Wir erheben folgende Daten:', 'privacy.s2.i1': 'Kontoinformationen.', 'privacy.s2.i2': 'Profilinformationen.', 'privacy.s2.i3': 'Erstellte Inhalte.', 'privacy.s2.i4': 'Technische Daten.', 'privacy.s3.title': '3. Datennutzung', 'privacy.s3.text': 'Wir nutzen die Daten für:', 'privacy.s3.i1': 'Kontoverwaltung.', 'privacy.s3.i2': 'Plattformfunktionen.', 'privacy.s3.i3': 'Verbesserung der Nutzererfahrung.', 'privacy.s3.i4': 'Sicherheit.', 'privacy.s4.title': '4. Datenweitergabe', 'privacy.s4.text': 'Wir verkaufen deine Daten nicht.', 'privacy.s4.i1': 'An Dienstleister.', 'privacy.s4.i2': 'Bei gesetzlicher Pflicht.', 'privacy.s5.title': '5. Cookies', 'privacy.s5.text': 'Wir verwenden essentielle Cookies.', 'privacy.s6.title': '6. Datensicherheit', 'privacy.s6.text': 'Passwörter werden verschlüsselt.', 'privacy.s7.title': '7. Deine Rechte', 'privacy.s7.text': 'Du hast das Recht auf:', 'privacy.s7.i1': 'Zugang zu deinen Daten.', 'privacy.s7.i2': 'Löschung deines Kontos.', 'privacy.s7.i3': 'Widerruf deiner Einwilligung.', 'privacy.s8.title': '8. Änderungen', 'privacy.s8.text': 'Wir können diese Richtlinie aktualisieren.', 'privacy.s9.title': '9. Kontakt', 'privacy.s9.text': 'Kontaktiere uns über die Plattform.',
    'terms.title': 'AGB', 'terms.updated': 'Letzte Aktualisierung:', 'terms.s1.title': '1. Annahme', 'terms.s1.text': 'Mit der Kontoerstellung akzeptierst du diese AGB.', 'terms.s2.title': '2. Berechtigung', 'terms.s2.text': 'Mindestens 13 Jahre alt.', 'terms.s3.title': '3. Benutzerkonto', 'terms.s3.text': 'Du verpflichtest dich:', 'terms.s3.i1': 'Korrekte Informationen anzugeben.', 'terms.s3.i2': 'Dein Passwort vertraulich zu halten.', 'terms.s3.i3': 'Unbefugte Nutzung zu melden.', 'terms.s4.title': '4. Benutzerinhalte', 'terms.s4.text': 'Du bist für deine Inhalte verantwortlich. Verboten:', 'terms.s4.i1': 'Illegale oder diskriminierende Inhalte.', 'terms.s4.i2': 'Falsche Informationen.', 'terms.s4.i3': 'Urheberrechtsverletzungen.', 'terms.s4.i4': 'Spam oder Werbung.', 'terms.s4.i5': 'Unangemessene Inhalte für Minderjährige.', 'terms.s5.title': '5. Geistiges Eigentum', 'terms.s5.text': 'Du behältst dein Urheberrecht.', 'terms.s6.title': '6. Moderation', 'terms.s6.text': 'Wir können Inhalte entfernen.', 'terms.s7.title': '7. Haftung', 'terms.s7.text': 'Die Plattform wird „wie besehen" bereitgestellt.', 'terms.s8.title': '8. Änderungen', 'terms.s8.text': 'Wir können diese AGB ändern.', 'terms.s9.title': '9. Kündigung', 'terms.s9.text': 'Du kannst dein Konto jederzeit schließen.', 'terms.s10.title': '10. Anwendbares Recht', 'terms.s10.text': 'Rumänisches Recht.',
    'notfound.title': 'Seite nicht gefunden', 'notfound.text': 'Diese Seite existiert nicht.', 'notfound.back': 'Zurück zur Startseite', 'footer.rights': 'Alle Rechte vorbehalten.', 'footer.privacy': 'Datenschutzrichtlinie', 'footer.terms': 'AGB',
  },
} as const;

type RoKeys = typeof translations.ro;

function createFallback(lang: string): Record<string, string> {
  return translations.en as unknown as Record<string, string>;
}

const allTranslations: Record<string, Record<string, string>> = {
  ...Object.fromEntries(
    Object.entries(translations).map(([k, v]) => [k, v as unknown as Record<string, string>])
  ),
};

const missingLangs: Language[] = ['it', 'pt', 'ru', 'zh', 'ja', 'ko', 'ar', 'hi', 'tr', 'pl', 'nl', 'sv', 'uk', 'cs', 'hu', 'bg', 'el', 'th', 'vi', 'id'];
for (const lang of missingLangs) {
  if (!allTranslations[lang]) {
    allTranslations[lang] = { ...allTranslations.en };
  }
}

allTranslations.it = { ...allTranslations.en, 'nav.home': 'Home', 'nav.life': 'Vita Scolastica', 'nav.hobbies': 'Hobby', 'nav.advice': 'Relazioni', 'category.sfaturi': 'Relazioni', 'nav.forum': 'Forum', 'nav.qa': 'Domande', 'nav.archive': 'Archivio', 'nav.login': 'Accedi', 'nav.logout': 'Esci', 'nav.darkmode': 'Modo scuro', 'nav.lightmode': 'Modo chiaro', 'nav.language': 'Lingua', 'hero.title': 'Diario di un adolescente cool', 'hero.subtitle': 'Un posto sicuro per i tuoi pensieri, nuovi amici e veri consigli.', 'latest.articles': 'Ultimi articoli', 'btn.readmore': 'Leggi di più', 'btn.create': 'Scrivi un articolo', 'btn.back': 'Indietro', 'btn.cancel': 'Annulla', 'btn.delete': 'Elimina', 'btn.like': 'Mi piace', 'btn.submit': 'Invia', 'auth.login.title': 'Accedi', 'auth.register.title': 'Crea account', 'auth.join': 'Unisciti alla comunità!', 'no.posts': 'Nessun post ancora.', 'create.post.submit': 'Pubblica', 'notfound.title': 'Pagina non trovata', 'notfound.text': 'La pagina cercata non esiste.', 'notfound.back': 'Torna alla home', 'footer.rights': 'Tutti i diritti riservati.' };

allTranslations.pt = { ...allTranslations.en, 'nav.home': 'Início', 'nav.life': 'Vida Escolar', 'nav.hobbies': 'Hobbies', 'nav.advice': 'Relacionamentos', 'category.sfaturi': 'Relacionamentos', 'nav.login': 'Entrar', 'nav.logout': 'Sair', 'nav.darkmode': 'Modo escuro', 'nav.lightmode': 'Modo claro', 'nav.language': 'Idioma', 'hero.title': 'Diário de um adolescente legal', 'hero.subtitle': 'Um lugar seguro para seus pensamentos, novos amigos e conselhos reais.', 'latest.articles': 'Últimos artigos', 'btn.readmore': 'Ler mais', 'btn.create': 'Escrever artigo', 'btn.back': 'Voltar', 'btn.cancel': 'Cancelar', 'auth.login.title': 'Entrar', 'auth.register.title': 'Criar conta', 'auth.join': 'Junte-se à comunidade!', 'no.posts': 'Nenhum post ainda.', 'create.post.submit': 'Publicar', 'notfound.title': 'Página não encontrada', 'notfound.back': 'Voltar ao início', 'footer.rights': 'Todos os direitos reservados.' };

allTranslations.ru = { ...allTranslations.en, 'nav.home': 'Главная', 'nav.life': 'Школьная жизнь', 'nav.hobbies': 'Хобби', 'nav.advice': 'Отношения', 'category.sfaturi': 'Отношения', 'nav.login': 'Войти', 'nav.logout': 'Выйти', 'nav.darkmode': 'Тёмная тема', 'nav.lightmode': 'Светлая тема', 'nav.language': 'Язык', 'hero.title': 'Дневник крутого подростка', 'hero.subtitle': 'Безопасное место для твоих мыслей, новых друзей и настоящих советов.', 'latest.articles': 'Последние статьи', 'btn.readmore': 'Читать далее', 'btn.create': 'Написать статью', 'btn.back': 'Назад', 'btn.cancel': 'Отмена', 'auth.login.title': 'Войти', 'auth.register.title': 'Создать аккаунт', 'auth.join': 'Присоединяйся к сообществу!', 'no.posts': 'Постов пока нет.', 'create.post.submit': 'Опубликовать', 'notfound.title': 'Страница не найдена', 'notfound.back': 'На главную', 'footer.rights': 'Все права защищены.' };

allTranslations.zh = { ...allTranslations.en, 'nav.home': '首页', 'nav.life': '校园生活', 'nav.hobbies': '兴趣爱好', 'nav.advice': '人际关系', 'category.sfaturi': '人际关系', 'nav.login': '登录', 'nav.logout': '退出', 'nav.darkmode': '暗色模式', 'nav.lightmode': '亮色模式', 'nav.language': '语言', 'hero.title': '酷少年的日记', 'hero.subtitle': '一个安全的地方，记录你的想法，交新朋友，获得真实的建议。', 'latest.articles': '最新文章', 'btn.readmore': '阅读更多', 'btn.create': '写文章', 'btn.back': '返回', 'btn.cancel': '取消', 'auth.login.title': '登录', 'auth.register.title': '创建账户', 'auth.join': '加入社区！', 'no.posts': '还没有帖子。', 'create.post.submit': '发布', 'notfound.title': '页面未找到', 'notfound.back': '返回首页', 'footer.rights': '版权所有。' };

allTranslations.ja = { ...allTranslations.en, 'nav.home': 'ホーム', 'nav.life': '学校生活', 'nav.hobbies': '趣味', 'nav.advice': '人間関係', 'category.sfaturi': '人間関係', 'nav.login': 'ログイン', 'nav.logout': 'ログアウト', 'nav.darkmode': 'ダークモード', 'nav.lightmode': 'ライトモード', 'nav.language': '言語', 'hero.title': 'クールなティーンの日記', 'hero.subtitle': 'あなたの考え、新しい友達、本物のアドバイスのための安全な場所。', 'latest.articles': '最新記事', 'btn.readmore': 'もっと読む', 'btn.create': '記事を書く', 'btn.back': '戻る', 'btn.cancel': 'キャンセル', 'auth.login.title': 'ログイン', 'auth.register.title': 'アカウント作成', 'auth.join': 'コミュニティに参加！', 'no.posts': 'まだ投稿がありません。', 'create.post.submit': '公開', 'notfound.title': 'ページが見つかりません', 'notfound.back': 'ホームに戻る', 'footer.rights': '全著作権所有。' };

allTranslations.ko = { ...allTranslations.en, 'nav.home': '홈', 'nav.life': '학교 생활', 'nav.hobbies': '취미', 'nav.advice': '관계', 'category.sfaturi': '관계', 'nav.login': '로그인', 'nav.logout': '로그아웃', 'nav.darkmode': '다크 모드', 'nav.lightmode': '라이트 모드', 'nav.language': '언어', 'hero.title': '멋진 10대의 일기', 'hero.subtitle': '당신의 생각, 새 친구, 진짜 조언을 위한 안전한 곳.', 'latest.articles': '최신 글', 'btn.readmore': '더 읽기', 'btn.create': '글 쓰기', 'btn.back': '뒤로', 'btn.cancel': '취소', 'auth.login.title': '로그인', 'auth.register.title': '계정 만들기', 'auth.join': '커뮤니티에 참여하세요!', 'no.posts': '아직 게시물이 없습니다.', 'create.post.submit': '게시', 'notfound.title': '페이지를 찾을 수 없습니다', 'notfound.back': '홈으로 돌아가기', 'footer.rights': '모든 권리 보유.' };

allTranslations.ar = { ...allTranslations.en, 'nav.home': 'الرئيسية', 'nav.life': 'الحياة المدرسية', 'nav.hobbies': 'الهوايات', 'nav.advice': 'العلاقات', 'category.sfaturi': 'العلاقات', 'nav.login': 'تسجيل الدخول', 'nav.logout': 'تسجيل الخروج', 'nav.darkmode': 'الوضع الداكن', 'nav.lightmode': 'الوضع الفاتح', 'nav.language': 'اللغة', 'hero.title': 'يوميات مراهق رائع', 'hero.subtitle': 'مكان آمن لأفكارك وأصدقائك الجدد ونصائح حقيقية.', 'latest.articles': 'أحدث المقالات', 'btn.readmore': 'اقرأ المزيد', 'btn.create': 'اكتب مقالاً', 'btn.back': 'رجوع', 'btn.cancel': 'إلغاء', 'auth.login.title': 'تسجيل الدخول', 'auth.register.title': 'إنشاء حساب', 'no.posts': 'لا توجد منشورات بعد.', 'create.post.submit': 'نشر', 'notfound.title': 'الصفحة غير موجودة', 'notfound.back': 'العودة للرئيسية', 'footer.rights': 'جميع الحقوق محفوظة.' };

allTranslations.hi = { ...allTranslations.en, 'nav.home': 'होम', 'nav.life': 'स्कूल जीवन', 'nav.hobbies': 'शौक', 'nav.advice': 'रिश्ते', 'category.sfaturi': 'रिश्ते', 'nav.login': 'लॉग इन', 'nav.logout': 'लॉग आउट', 'nav.darkmode': 'डार्क मोड', 'nav.lightmode': 'लाइट मोड', 'nav.language': 'भाषा', 'hero.title': 'एक कूल किशोर की डायरी', 'hero.subtitle': 'आपके विचारों, नए दोस्तों और सच्ची सलाह के लिए एक सुरक्षित जगह।', 'latest.articles': 'नवीनतम लेख', 'btn.readmore': 'और पढ़ें', 'btn.create': 'लेख लिखें', 'auth.login.title': 'लॉग इन', 'auth.register.title': 'खाता बनाएं', 'no.posts': 'अभी तक कोई पोस्ट नहीं।', 'create.post.submit': 'प्रकाशित', 'notfound.title': 'पृष्ठ नहीं मिला', 'notfound.back': 'होम पर वापस जाएं', 'footer.rights': 'सर्वाधिकार सुरक्षित।' };

allTranslations.tr = { ...allTranslations.en, 'nav.home': 'Ana Sayfa', 'nav.life': 'Okul Hayatı', 'nav.hobbies': 'Hobiler', 'nav.advice': 'İlişkiler', 'category.sfaturi': 'İlişkiler', 'nav.login': 'Giriş Yap', 'nav.logout': 'Çıkış Yap', 'nav.darkmode': 'Karanlık mod', 'nav.lightmode': 'Aydınlık mod', 'nav.language': 'Dil', 'hero.title': 'Havalı Bir Gencin Günlüğü', 'hero.subtitle': 'Düşüncelerin, yeni arkadaşlıklar ve gerçek tavsiyeler için güvenli bir yer.', 'latest.articles': 'Son Yazılar', 'btn.readmore': 'Devamını Oku', 'btn.create': 'Yazı Yaz', 'auth.login.title': 'Giriş Yap', 'auth.register.title': 'Hesap Oluştur', 'no.posts': 'Henüz yazı yok.', 'create.post.submit': 'Yayınla', 'notfound.title': 'Sayfa bulunamadı', 'notfound.back': 'Ana sayfaya dön', 'footer.rights': 'Tüm hakları saklıdır.' };

allTranslations.pl = { ...allTranslations.en, 'nav.home': 'Strona główna', 'nav.life': 'Życie szkolne', 'nav.hobbies': 'Hobby', 'nav.advice': 'Relacje', 'category.sfaturi': 'Relacje', 'nav.login': 'Zaloguj się', 'nav.logout': 'Wyloguj się', 'nav.darkmode': 'Tryb ciemny', 'nav.lightmode': 'Tryb jasny', 'nav.language': 'Język', 'hero.title': 'Pamiętnik fajnego nastolatka', 'hero.subtitle': 'Bezpieczne miejsce na twoje myśli, nowych przyjaciół i prawdziwe porady.', 'latest.articles': 'Najnowsze artykuły', 'btn.readmore': 'Czytaj więcej', 'btn.create': 'Napisz artykuł', 'auth.login.title': 'Zaloguj się', 'auth.register.title': 'Utwórz konto', 'no.posts': 'Brak postów.', 'create.post.submit': 'Opublikuj', 'notfound.title': 'Strona nie znaleziona', 'notfound.back': 'Wróć do strony głównej', 'footer.rights': 'Wszelkie prawa zastrzeżone.' };

allTranslations.nl = { ...allTranslations.en, 'nav.home': 'Home', 'nav.login': 'Inloggen', 'nav.logout': 'Uitloggen', 'nav.darkmode': 'Donkere modus', 'nav.lightmode': 'Lichte modus', 'nav.language': 'Taal', 'hero.title': 'Dagboek van een coole tiener', 'hero.subtitle': 'Een veilige plek voor je gedachten, nieuwe vrienden en echte adviezen.', 'latest.articles': 'Laatste artikelen', 'btn.readmore': 'Lees meer', 'btn.create': 'Schrijf een artikel', 'auth.login.title': 'Inloggen', 'auth.register.title': 'Account aanmaken', 'no.posts': 'Nog geen berichten.', 'notfound.title': 'Pagina niet gevonden', 'notfound.back': 'Terug naar home', 'footer.rights': 'Alle rechten voorbehouden.' };

allTranslations.sv = { ...allTranslations.en, 'nav.home': 'Hem', 'nav.login': 'Logga in', 'nav.logout': 'Logga ut', 'nav.darkmode': 'Mörkt läge', 'nav.lightmode': 'Ljust läge', 'nav.language': 'Språk', 'hero.title': 'Dagbok av en cool tonåring', 'latest.articles': 'Senaste artiklarna', 'btn.readmore': 'Läs mer', 'btn.create': 'Skriv en artikel', 'auth.login.title': 'Logga in', 'auth.register.title': 'Skapa konto', 'notfound.title': 'Sidan hittades inte', 'notfound.back': 'Tillbaka till startsidan', 'footer.rights': 'Alla rättigheter förbehållna.' };

allTranslations.uk = { ...allTranslations.en, 'nav.home': 'Головна', 'nav.login': 'Увійти', 'nav.logout': 'Вийти', 'nav.darkmode': 'Темна тема', 'nav.lightmode': 'Світла тема', 'nav.language': 'Мова', 'hero.title': 'Щоденник крутого підлітка', 'latest.articles': 'Останні статті', 'btn.readmore': 'Читати далі', 'btn.create': 'Написати статтю', 'auth.login.title': 'Увійти', 'auth.register.title': 'Створити акаунт', 'notfound.title': 'Сторінку не знайдено', 'notfound.back': 'На головну', 'footer.rights': 'Усі права захищені.' };

allTranslations.cs = { ...allTranslations.en, 'nav.home': 'Domů', 'nav.login': 'Přihlásit se', 'nav.logout': 'Odhlásit se', 'hero.title': 'Deník cool teenagera', 'btn.create': 'Napsat článek', 'notfound.title': 'Stránka nenalezena', 'footer.rights': 'Všechna práva vyhrazena.' };
allTranslations.hu = { ...allTranslations.en, 'nav.home': 'Kezdőlap', 'nav.login': 'Bejelentkezés', 'nav.logout': 'Kijelentkezés', 'hero.title': 'Egy menő tizenéves naplója', 'btn.create': 'Cikk írása', 'notfound.title': 'Az oldal nem található', 'footer.rights': 'Minden jog fenntartva.' };
allTranslations.bg = { ...allTranslations.en, 'nav.home': 'Начало', 'nav.login': 'Вход', 'nav.logout': 'Изход', 'hero.title': 'Дневникът на готин тийнейджър', 'btn.create': 'Напиши статия', 'notfound.title': 'Страницата не е намерена', 'footer.rights': 'Всички права запазени.' };
allTranslations.el = { ...allTranslations.en, 'nav.home': 'Αρχική', 'nav.login': 'Σύνδεση', 'nav.logout': 'Αποσύνδεση', 'hero.title': 'Ημερολόγιο ενός cool εφήβου', 'btn.create': 'Γράψε ένα άρθρο', 'notfound.title': 'Η σελίδα δεν βρέθηκε', 'footer.rights': 'Με επιφύλαξη παντός δικαιώματος.' };
allTranslations.th = { ...allTranslations.en, 'nav.home': 'หน้าแรก', 'nav.login': 'เข้าสู่ระบบ', 'nav.logout': 'ออกจากระบบ', 'hero.title': 'ไดอารี่ของวัยรุ่นสุดเจ๋ง', 'btn.create': 'เขียนบทความ', 'notfound.title': 'ไม่พบหน้า', 'footer.rights': 'สงวนลิขสิทธิ์' };
allTranslations.vi = { ...allTranslations.en, 'nav.home': 'Trang chủ', 'nav.login': 'Đăng nhập', 'nav.logout': 'Đăng xuất', 'hero.title': 'Nhật ký của một thiếu niên tuyệt vời', 'btn.create': 'Viết bài', 'notfound.title': 'Không tìm thấy trang', 'footer.rights': 'Bảo lưu mọi quyền.' };
allTranslations.id = { ...allTranslations.en, 'nav.home': 'Beranda', 'nav.login': 'Masuk', 'nav.logout': 'Keluar', 'hero.title': 'Buku Harian Remaja Keren', 'btn.create': 'Tulis Artikel', 'notfound.title': 'Halaman tidak ditemukan', 'footer.rights': 'Hak cipta dilindungi.' };

interface LangState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLang = create<LangState>()(
  persist(
    (set, get) => ({
      language: 'ro',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        const dict = allTranslations[lang] || allTranslations.en;
        return dict[key] || allTranslations.en[key] || key;
      },
    }),
    {
      name: 'jurnalul-language',
      partialize: (state) => ({ language: state.language }),
    }
  )
);
